drop table if exists disk_item ;
drop table if exists disk_item_history;

create table disk_item
(
    disk_item_id        varchar(255) not null,
    disk_item_date      TIMESTAMP WITHOUT TIME ZONE not null,
    disk_item_parent_id varchar(255),
    disk_item_size      int8,
    disk_item_type      varchar(255) not null,
    disk_item_url       varchar(255),
    primary key (disk_item_id)
);
create table disk_item_history
(
    disk_item_history_id int8 generated by default as identity,
    disk_item_date       TIMESTAMP WITHOUT TIME ZONE not null,
    disk_item_parent_id  varchar(255),
    disk_item_size       int8,
    disk_item_type       varchar(255) not null,
    disk_item_url        varchar(255),
    disk_item_id         varchar(255),
    primary key (disk_item_history_id)
);